project:
  type: website

website:
  title: "The Open Data Lab"
  google-analytics: "G-F3NM2QR1Y0"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: stories.qmd
        text: Stories
      - href: projects.qmd
        text: Projects & Research
      - href: contributors.qmd
        text: People
      - href: publications-media.qmd
        text: Media
    right:
      - icon: github
        href: https://github.com/martinezc1
  page-footer:
    left: |
      © 2026 The Open Data Lab  
      Built with Quarto  
      *Founded by Christian A. Martinez (CUNY)*

    right: |
      [GitHub](https://github.com/nyc-open-data-lab)  
      [LinkedIn](https://www.linkedin.com/company/nyc-open-data-lab/)  
      [Email](mailto:c.martinez0@outlook.com)

format:
  html:
    theme:
      - quartz
      - brand
    css: styles.css
    toc: true

editor: visual