---
title: "Emma Tupone"
description: "Civic Data Application Development Intern"
---

## Summary

As the Civic Data Application Development intern, they are currently using the NYC Open Data platform and the `nycOpenData` R package to develop web-based analytical tools that allow users to explore civic datasets through intuitive dashboards and interactive visualizations.

Learn more about the internship [here](../internships/civic-data.qmd).

## Projects & Publications

- [Environmental Stressors and Social Complaints in New York City](https://martinezc1-nyc-open-data-student-gallery.share.connect.posit.cloud/chapters/07-EnvironmentalStressorsandSocialComplaintsNYC-Emma.html)
- Presented research at [**NYC Open Data Week 2026**](../publications-media.qmd#sec-nyc-open-data-week-2026) as part of the Lab's NYC Open Data Student Gallery presentation

------------------------------------------------------------------------

## Portfolio

A curated collection of work developed using reproducible workflows in R and Quarto.

- 📘 [View Portfolio Book](https://martinezc1-reproducible-research-using-r--student-work-in-pract.share.connect.posit.cloud/chapters/emma-tupone.html)

------------------------------------------------------------------------

## Contributions to the Lab

Emma has contributed to the expansion of the [**OpenData R package ecosystem**](../projects.qmd#sec-package-ecosystem) through the development of `ausOpenData` using the Lab's *OpenData Package Developer's Guide*. She also contributed research to the [**NYC Open Data Student Gallery**](../projects.qmd#sec-nyc-opendata-student-gallery), helping demonstrate how open public data can be used for reproducible student research.

------------------------------------------------------------------------

## Links

- [GitHub](https://github.com/emmatup0205)\
- [LinkedIn](https://www.linkedin.com/in/emma-tupone-1353a1291/)\
- [ORCID](https://orcid.org/0009-0001-7207-0986)
