---
title: "Jonah Dratfield"
description: "Public Engagement & Partnerships Associate"
---

## Summary

As the Public Engagement & Partnerships Associate, they help connect the Lab’s work to broader communities and opportunities. Their work focuses on communicating the public and civic value of Lab projects, developing partnerships with external organizations, and researching career and workforce pathways that can help students translate their skills into meaningful opportunities.

## Projects & Publications

- [**Social Infrastructure & Well-Being**](https://martinezc1-nyc-open-data-student-gallery.share.connect.posit.cloud/chapters/02-Final-Social-Infrastructure-and-Well-Being-Jonah.html)
- Presented research at [**NYC Open Data Week 2026**](../talks.qmd#sec-nyc-open-data-week-2026) as part of the Lab's NYC Open Data Student Gallery presentation
- [**The Impact Speed Cameras Have on Safety**](../stories/crash-data.qmd)

------------------------------------------------------------------------

## Portfolio

A curated collection of work developed using reproducible workflows in R and Quarto.

- 📘 [View Portfolio Book](https://martinezc1-reproducible-research-using-r--student-work-in-pract.share.connect.posit.cloud/chapters/jonah-dratfield.html)

------------------------------------------------------------------------

## Contributions to the Lab

- Contributor to the NYC Open Data Student Gallery\
- Contributor to the development of the `nycOpenData` R package

------------------------------------------------------------------------

## Links

- [GitHub](https://github.com/jdratfield38)\
- [LinkedIn](https://www.linkedin.com/in/jonah-dratfield-932584167/)\
- [ORCID](https://orcid.org/0009-0005-6153-2590)
