---
title: "Xinru Wang"
description: "Text Analytics & Computational Social Science Intern"
---

## Summary

As a Text Analytics & Computational Social Science Intern, they use reproducible research methods to explore language through data, analyzing publicly available text to uncover patterns in communication, sentiment, and public discourse.

Learn more about the internship [here](../internships/test-analysis-internship.qmd).

## Projects & Publications

- [Beating Around the Bush: Uncovering the Hidden Link Between Urban Trees and Wildlife Activity](https://martinezc1-nyc-open-data-student-gallery.share.connect.posit.cloud/chapters/08-Beating-Around-the-Bush--Uncovering-the-Hidden-Link-Between-Urban-Trees-and-Wildlife-Activity-Xinru.html)
- Presented research at [**NYC Open Data Week 2026**](../talks.qmd#sec-nyc-open-data-week-2026) as part of the Lab's NYC Open Data Student Gallery presentation

------------------------------------------------------------------------

## Portfolio

A curated collection of work developed using reproducible workflows in R and Quarto.

- 📘 [View Portfolio Book](https://martinezc1-reproducible-research-using-r--student-work-in-pract.share.connect.posit.cloud/chapters/xinru-wang.html)

------------------------------------------------------------------------

## Contributions to the Lab

- Contributor to the NYC Open Data Student Gallery\
- Contributor to the development of the `nycOpenData` R package

------------------------------------------------------------------------

## Links

- [GitHub](https://github.com/xrwangxr)\
- [LinkedIn](https://www.linkedin.com/in/xinru-wang-798937393/)\
- [ORCID](https://orcid.org/0009-0006-3833-8199)
